#!/usr/bin/make -f
## makefile (for cargo)
## Mac Radigan

.PHONY: build clean run
.DEFAULT_GOAL := build

default: build

build:
	$(MAKE) -C hello $@

clean:
	$(MAKE) -C hello $@

run:
	$(MAKE) -C hello $@

## *EOF*
