#!/usr/bin/make
## makefile
## Mac Radigan

.PHONY:
.DEFAULT_GOAL := hello-cxx hello-java

default: build

build:
	$(MAKE) -C hello-cxx $@
	$(MAKE) -C hello-java $@

clean:
	$(MAKE) -C hello-cxx $@
	$(MAKE) -C hello-java $@

## *EOF*
