#!/usr/bin/make -f
## makefile (for stack)
## Mac Radigan

.PHONY: build clean run install
.DEFAULT_GOAL := build

default: build

build:
	stack $@

install:
	stack $@

clean:
	stack $@

run:
	~/.local/bin/hello-exe

## *EOF*
