#!/usr/bin/make
## makefile (for stack)
## Mac Radigan

.PHONY: build clean run install
.DEFAULT_GOAL := build

default: build

build:
	stack $@

intstall:
	stack $@

clean:
	stack $@

run:
	~/.local/bin/hello-exe

## *EOF*
