#!/usr/bin/make
## makefile (for stack)
## Mac Radigan

.PHONY: build clean run install
.DEFAULT_GOAL := build

default: build

build:
	$(MAKE) -C hello $@

install:
	$(MAKE) -C hello $@

clean:
	$(MAKE) -C hello $@

run:
	$(MAKE) -C hello $@

## *EOF*
